apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: memory-stress
        image: aryansingh163/memory-stress:latest
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "2Gi"
