apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        tag: service-a
    spec:
      containers:
      - name: memory-stress
        image: aryansingh163/memory-stress
        ports:
        - containerPort: 80